// config.ts -- the only place that reads the environment. Depends on: nothing.

/**
 * One connection string per role, because one connection string would mean one set of
 * privileges and the whole point is that these three cannot do the same things.
 *
 * There is no fallback between them on purpose. Letting the auditor quietly borrow the
 * application's URL, or the application borrow the owner's, would mean a deployment that
 * forgot to configure a role runs with more power than it asked for and nothing says so.
 * A missing variable is a startup failure with a message; a silent fallback is a hole.
 */
export type DatabaseRole = "DATABASE_URL" | "DATABASE_ADMIN_URL" | "DATABASE_AUDITOR_URL";

const ROLES: Readonly<Record<DatabaseRole, string>> = {
  DATABASE_URL: "the application role: may read and append, never update or delete",
  DATABASE_ADMIN_URL: "the owning role: runs migrations, provisions logins, sets up test data",
  DATABASE_AUDITOR_URL: "the read-only role the reconciliation job runs as",
};

export type Config = {
  readonly databaseUrl: string;
};

/**
 * Fails at startup rather than at the first query. A process that boots half-configured
 * is worse than one that refuses to boot.
 */
export function requireDatabaseUrl(
  role: DatabaseRole,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const url = env[role]?.trim();

  if (url === undefined || url.length === 0) {
    throw new Error(
      `${role} is not set. It is ${ROLES[role]}. ` +
        "Copy .env.example to .env, then run `npm run provision` so the roles it names exist.",
    );
  }

  return url;
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): Config {
  return { databaseUrl: requireDatabaseUrl("DATABASE_URL", env) };
}

export type ServerConfig = {
  readonly databaseUrl: string;
  readonly port: number;
};

const DEFAULT_PORT = 8080;

/**
 * The server connects with DATABASE_URL, never with the owner's. It has no business
 * migrating anything, and the role it runs as is what makes a posting immutable.
 *
 * There is no API token here any more, and its absence is the change rather than a
 * simplification. A single shared secret in the environment could not be attributed to a
 * caller, could not be revoked without a restart, and could be set to whatever the operator
 * felt like typing -- so the server used to have to check that it was at least long enough
 * to not be a word. Credentials now live in the database, are generated by `issue-key`
 * rather than chosen, and are revoked by `revoke-key` while the process keeps running. What
 * the environment still decides is where to connect and where to listen.
 */
export function loadServerConfig(env: NodeJS.ProcessEnv = process.env): ServerConfig {
  return {
    databaseUrl: requireDatabaseUrl("DATABASE_URL", env),
    port: readPort(env["PORT"]),
  };
}

function readPort(raw: string | undefined): number {
  if (raw === undefined || raw.trim().length === 0) {
    return DEFAULT_PORT;
  }

  // Written out rather than left to Number(), which reads "8080abc" as NaN but "0x1f90" as
  // 8080 and " 80 " as 80. A port that was mistyped should stop the process, not bind
  // something plausible.
  if (!/^\d{1,5}$/.test(raw.trim())) {
    throw new Error(`PORT must be a number between 0 and 65535, got ${JSON.stringify(raw)}`);
  }

  const port = Number(raw.trim());
  if (port > 65535) {
    throw new Error(`PORT must be a number between 0 and 65535, got ${port}`);
  }
  return port;
}
